name: evil deploy

on:
  pull_request:

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cache-
